### ISSUE TITLE
`bin/rails console` does not work

### ISSUE THREAD

**Issue by danielskowronski** [KSIUJ/ksi-erc#17]
Could not find autoprefixer-rails-6.0.3 in any of the sources
Run `bundle install` to install missing gems.

**Comment by ArcCha** [comment]
Who cares? It's not a bug.

**Comment by danielskowronski** [comment]
but how do I do anything in rails then?

**Comment by ArcCha** [comment]
Emm, it works for me. Also on production.

**Comment by danielskowronski** [comment]
Log in as root and check.
